version: '2'

services:
# auth service
  apigw:
    image: hub.dstorage.com/dstorage/auth
    networks:
      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    labels:
      - "traefik.backend=auth"
      - "traefik.frontend.rule=Host:auth.dstorage.com"
      - "traefik.docker.port=8080"
# upload service
  upload:
    image: hub.dstorage.com/filestore/upload
    networks:
      - web
    volumes:
      - /data/dstorage:/data/dstorage
      - /data/dstorage_part:/data/dstorage_part
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    labels:
      - "traefik.backend=upload"
      - "traefik.frontend.rule=Host:upload.dstorage.com"
      - "traefik.docker.port=28080"
# download service
  download:
    image: hub.dstorage.com/filestore/download
    networks:
      - web
    volumes:
      - /data/dstorage:/data/dstorage
      - /data/dstorage_part:/data/dstorage_part
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    labels:
      - "traefik.backend=download"
      - "traefik.frontend.rule=Host:download.dstorage.com"
      - "traefik.docker.port=38080"
# user service
  account:
    image: hub.dstorage.com/filestore/user
    networks:
      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
# transfer service
  transfer:
    image: hub.dstorage.com/filestore/transfer
    networks:
      - web
    volumes:
      - /data/dstorage:/data/dstorage
      - /data/dstorage_part:/data/dstorage_part
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
# dbproxy service
  dbproxy:
    image: hub.dstorage.com/filestore/dbproxy
    networks:
      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
networks:
  web:
    external:
      name: dstorage